language: java

before_install: mvn install assembly:single -DskipTests=true -DfinalName=sharpen
install: mvn test

deploy:
  provider: releases
  api_key:
    secure: "biqWHeia1J9FPDtujYYROXefqRdRbpP8GAeUVNeBm2A4dW5muI5CG0LirQlOQ/wvKnPbJzhXwh3oXvPdbiAEGGCozpmy/P33m3C3tDP+fCe/C1hWwu6ib2fslaaPYnH2X0xX2lc8qHKxRGZsLE3uHFubr5/7IRl9z+r8ia32b+4="
  file:  sharpen.core/target/sharpen$-jar-with-dependencies.jar

  skip_cleanup: true
  on:
    all_branches: true