language: java
before_install: mvn install assembly:single -DskipTests=true -DfinalName=sharpen
install: mvn test
deploy:
  provider: releases
  api_key:
    secure: rnPlroNjSSnd0sPMZimjvt+A3wv9yNwDoKtdj1j3elxdkU/ANYyXZZEvZ9lVr8/iWVmixEem74WftsqtDhglRhu1rugdxJLJx7+8KOXQu8IJu0iEsd/YgjZrASV9b73ejGIZngay4XFRJco0wXjkS42443SrkQ2c/iQmquL8WjM=
  file: sharpen.core/target/sharpen$-jar-with-dependencies.jar
  skip_cleanup: true
  on:
    repo: avasp/sharpen
    all_branches: true
